language: haskell
sudo: false

cache:
  directories:
    - $HOME/.cabal/

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.4.2 HAPPYVER=1.19.5 ALEXVER=3.1.7
      compiler: ": #GHC 7.4.2"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.4.2,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.6.3 HAPPYVER=1.19.5 ALEXVER=3.1.7
      compiler: ": #GHC 7.6.3"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4 HAPPYVER=1.19.5 ALEXVER=3.1.7
      compiler: ": #GHC 7.8.4"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3 HAPPYVER=1.19.5 ALEXVER=3.1.7
      compiler: ": #GHC 7.10.3"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1 HAPPYVER=1.19.5 ALEXVER=3.1.7
      compiler: ": #GHC 8.0.1"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
      compiler: ": #GHC head"
      addons: {apt: {packages: [cabal-install-1.24,ghc-head,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}

  allow_failures:
   - env: CABALVER=1.24 GHCVER=head


before_install:
  - unset CC
  - export PATH=~/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install --only-dependencies --enable-tests

