name:                hopes
version:             0.0.5
github:              "acharal/hopes"
license:             GPL
author:              "Angelos Charalambidis"
maintainer:          "a.charalambidis@di.uoa.gr"
copyright:           "2006-2011 Angelos Charalambidis"

extra-source-files:
- README.md

build-tools:
- happy

# Metadata used when publishing your package
synopsis:            Higher Order Prolog with Extensional Semantics
category:            Compilers/Interpreters

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Hopes is a prototype interpreter for a subset of Higher Order Logic
  used as Programming Language.

dependencies:
- base
- array
- pretty

when:
- condition: os(windows)
  cpp-options: -DBUILD_WINDOWS
  dependencies:
  - Win32

executables:
  hopes:
    main:                Main.hs
    source-dirs:
    - src
    - src/basic
    - src/frontend
    - src/prover
    - src/interpreter
    generated-other-modules:
    - Paths_hopes
    other-modules:
    - Language.Hopl
    - ComputedAnswer
    - CoreLang
    - Debugger
    - Derive
    - Desugar
    - Driver
    - Error
    - HopesIO
    - Infer
    - Infer.Class
    - Lang
    - Language.Hopl.Pretty
    - Language.Hopl.Syntax
    - Language.Hopl.Syntax.Pretty
    - Lexer
    - Loc
    - Logic
    - Logic.Class
    - Logic.SFK
    - ParseUtils
    - Parser
    - Pretty
    - Restrict
    - Shell
    - Subst
    - Tc
    - Trace
    - Trace.Class
    - Trace.Coroutine
    - TypeCheck
    - Types
    - Unify
    - WellForm
    when:
    - condition: flag(dc-impl)
      dependencies:
      - CC-delcont-cxe
      cpp-options: -DDCIMPL
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl
    - haskeline
    - monad-coroutine

tests:
  hopes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

flags:
  dc-impl:
    description: Choose the alternative implementation of prover using delimited continuations
    default: false
    manual: true
