name: 'ci'
on: [ 'push' ]
jobs:
  build:    
    runs-on: ubuntu-18.04
    
    steps:
    - uses: 'actions/checkout@v1'
    - uses: 'mstksg/setup-stack@v1'
    - uses: 'actions/cache@v1'
      with:
        path: '~/.stack'
        key: "${{ runner.os }}-stack"
    - run: 'stack build'
